### ISSUE TITLE
How to get properties?

### ISSUE THREAD

**Issue by xeruf** [TangoraBox/ComponentInspector#2]
Thank you, this is quite helpful already to find what is going wrong in my layouting. But the description also mentions the possibility to see properties, which would be extraordinarily helpful, is this implemented, too?

**Comment by garzy** [comment]
I'm glad my component is being useful to you ;)

That feature shows what name has been used by the parent to define the child you are inspecting (the one you have your mouse over).

For it to work, the parent class must have the child as a class field, otherwise, it doesn't work because it is searched by reflection in the parent class.

For example, if you see [this code](https://github.com/TangoraBox/ComponentInspector/blob/master/javafx-example/src/main/java/com/tangorabox/componentinspector/fx/JavaFXWindowPanel.java)

When you are over the "panelUp" Hbox, you will see "panelUp" in the parent box of the Component Inspector popup.

_Please, feel free to request any feature, maybe you want to see some CSS properties or something else properties of the inspected component?_

**Comment by xeruf** [comment]
I would like to see detailed (layout) properties of a node (preferred width, height, bounds, insets, padding, ...), maybe in a separate window or popup or simply the log.
I also found https://github.com/JonathanGiles/scenic-view in the meantime, but did not get it to work yet...

**Comment by garzy** [comment]
Scenic-View is an incredible tool that will be more accorded to your needs. 

> To use Scenic-View you must install it as a standalone desktop app and launch it. Then, when you launch your application, Scenic-View will found your JVM and will show the application component's hierarchy.

 My Component Inspector is more intended for "fast prototyping" and also for finding the component class source file that you need to edit to make the desired change. Really useful if you are on a new project and you don't know the GUI java classes architecture.
